cc_binary(
    name = "initialization_order_example",
    srcs = [
        "logger.cc",
        "logger.h",
        "main.cc",
        "program_info.cc",
        "program_info.h",
        "safe_logger.cc",
        "safe_logger.h",
    ],
)
