cc_binary(
    name = "template_specialization",
    srcs = [
        "container.h",
        "main.cc",
    ],
)

cc_binary(
    name = "traits_example",
    srcs = [
        "traits_example.h",
        "traits_main.cc",
    ],
)
