cc_binary(
    name = "constinit_example",
    srcs = [
        "constinit_demo.h",
        "main.cc",
    ],
)

cc_binary(
    name = "consteval_example",
    srcs = [
        "consteval_demo.h",
        "consteval_main.cc",
    ],
)
